<?php
$plugin->includeJSSDK();
?>
<div class="am-fb-like-button-wrapper">
    <div class="am-fb-like-button">
        <div class="fb-like" data-send='true' data-href="<?php p($plugin->getConfig('likeurl', ROOT_URL)) ?>" data-width='450' data-layout="<?php p($plugin->getConfig('layout', 'standard')) ?>" data-action="<?php p($plugin->getConfig('action', 'like')) ?>" data-show-faces="true" data-share="true"></div>
    </div>
</div>