<?php $this->headMeta()->setName('robots', 'noindex,nofollow'); ?>
<?php
$body_class = "am-page-cc";
$title=___('Payment Info'); $this->setLayout('layout.phtml');

$this->headScript()
        ->appendFile($this->_scriptJs('jquery/jquery.validate.js'));
?>
<?php include $this->_script('_error.phtml'); ?>

<?php if (!empty($display_receipt)): ?>
<?php include $this->_script('_receipt.phtml'); ?>
<?php endif ?>

<?php echo $this->blocks('cc/form/top', "%s", array('invoice'=>@$invoice)); ?>
<?php include $this->_script('_form.phtml'); ?>
<?php include $this->_script('js.country_state.js'); ?>
<?php echo $this->blocks('cc/form/bottom', "%s", array('invoice'=>@$invoice)); ?>