<?php
$title = ___("iDEAL betaling");
$this->setLayout('layout.phtml');
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->public; ?>/style.css">

<table id="outer">
<tr>
    <td align="center">
    <img src="<?php echo $this->public; ?>/ideal.gif" align="right">
    <h2>iDEAL betaling</h2>
    <b>Selecteer uw bank</b><br/>Selecteer uw bank en klik op 'Verder' om door te<br/>gaan naar het iDEAL betaalscherm van uw bank.
    <br/><br/>

    <form method="post" action="<?php echo $this->action; ?>" target="_top">
    <input type="hidden" name="ec" value="<?php echo $this->payment_id; ?>">
    
    <table id="inner">
    <tr>
        <td><b>Omschrijving</b></td><td width="300px"><?php echo $this->description; ?></td>
    </tr>
    <tr>
        <td><b>Bedrag</b></td><td><?php echo number_format($this->price, 2, ',', ''); ?></td>
    </tr>
    <tr>
        <td><b>Uw bank</b></td><td><?php echo $this->banksSelect; ?></td>
    </tr>
    </table>

    <br/><br/>

    <input type="submit" value="Verder" />
    </form>

    </td>
</tr></table>

