<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="robots" content="noindex,nofollow" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <?php echo $this->headMeta() . "\n"; ?>
        <title><?php p(strip_tags($title)) ?></title>
        <?php
        $this->adminHeadInit();
        echo $this->headLink() . "\n";
        echo $this->headStyle() . "\n";
        echo $this->headScript() . "\n";
        ?>
    </head>
    <body>
        <?php echo $content ?>
    </body>
</html>