<?php
if (empty($title)) $title = ___('Shopping Cart');
$this->layoutNoTitle = true;
$this->setLayout('layout.phtml');
$this->headLink()->appendStylesheet($this->_scriptCss('cart.css'));
$this->headScript()
        ->appendFile($this->_scriptJs('cart.js'));
?>
<div class="am-cart <?php echo $this->blocks()->get('cart/right')?'':'am-cart-nosidebar'?>">
    <div class="am-cart-main">
        <div>
        <?php if(!empty($header)) : ?>
            <h2><?php p($header) ?></h2>
            <?php if (!empty($description)) : ?>
            <p class="am-cart-category-desc"><?php echo $description; ?></p>
            <?php endif; ?>
        <?php endif;?>
        <div class="am-cart-error">
            <?php include $this->_script('_error.phtml'); ?>
        </div>
        <?php echo $content ?>
        </div>
    </div>
    <div class="am-cart-sidebar">
    <?php echo $this->blocks('cart/right', '<h2 id="%3$s-head">%2$s</h2><div class="am-block block" id="%3$s">%1$s</div>');?>
    </div>
</div>
<?php include $this->_script('cart/_js.phtml');