<?php
Am_Di::getInstance()->plugins_protect->get('wordpress')
    ->startLayout($this, isset($meta_title) ? $meta_title : $title, true, $body_class);
ob_start();
get_header();
$_ =ob_get_clean();
echo str_replace(' has-sidebar', '', $_); ?>
<div id="main-content" class="main-content">
    <div id="primary" class="content-area">
        <div id="content" class="site-content" role="main">
            <?php include dirname(__FILE__)."/../amember.php"; ?>
        </div>
    </div>
</div>
<?php get_footer();