<?php
/**
 * Class represents records from table pages
 * {autogenerated}
 * @property int $link_id 
 * @property string $title 
 * @property string $url 
 * @property datetime $dattm 
 * @see Am_Table
 */
class Link extends ResourceAbstract {
    public function getUrl()
    {
        return $this->url;
    }
}

class LinkTable extends ResourceAbstractTable {
    protected $_key = 'link_id';
    protected $_table = '?_link';
    protected $_recordClass = 'Link';

    public function getAccessType()
    {
        return ResourceAccess::LINK;
    }
    public function getAccessTitle()
    {
        return ___('Links');
    }
    public function getPageId()
    {
        return 'links';
    }
}
