<?php $this->headMeta()->setName('robots', 'noindex,nofollow'); ?>
<?php $title = ___('Payment Failed'); $this->setLayout('layout.phtml'); ?>
<?php include $this->_script('_error.phtml'); ?>
<ul class="errors">
    <li><?php __e('An error occurred while handling your payment or you cancelled it.') ?></li>
</ul>
<h2><?php __e('Choose another payment processor or try again with the same.') ?></h2>
<?php echo $form; ?>


