<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title><?php p(isset($meta_title) ? $meta_title : $title) ?></title>
        <?php $this->printLayoutHead(); ?>
    </head>
    <body<?php if (!empty($body_class)): ?> class="<?php p($body_class) ?>"<?php endif; ?>>
        <?php echo $content ?>
    </body>
</html>