<?php
/**
 * This template displays payment receipt and
 * has one button to confirm payment
 */
$title = ___('Confirm Payment');
$this->layoutNoMenu = true;
$this->setLayout('layout.phtml');
if (empty($btnText)) $btnText = ___('Make Payment');

include $this->_script('_receipt.phtml');
?>
<div class="make-payment-button">
    <form method="post" action="<?php p($url); ?>">
        <input type="submit" name="do" value="<?php p($btnText) ?>" />
        <?php if (!empty($hidden)) echo Am_Html::renderArrayAsInputHiddens($hidden); ?>
    </form>
</div>