<?php _e("This shortcode will output information about logged in user. Can be used without any parameters (will output user's full name then).", 'am4-plugin');?>
<br/><br/>
<table>
<tr><th><span class="am4shortcode">[am4user]</span></th><td>John Doe</td></tr>
<tr><th><span class="am4shortcode">[am4user var=user_id]</span></th><td>1</td></tr>
<tr><th><span class="am4shortcode">[am4user var=login]</span></th><td>johndoe</td></tr>
<tr><th><span class="am4shortcode">[am4user var=email]</span></th><td>johndoe@example.com</td></tr>
<tr><th><span class="am4shortcode">[am4user var=name_f]</span></th><td>John</td></tr>
<tr><th><span class="am4shortcode">[am4user var=name_l]</span></th><td>Doe</td></tr>
<tr><th><span class="am4shortcode">[am4user var=city]</span></th><td>New York</td></tr>
<tr><th><span class="am4shortcode">[am4user var=state]</span></th><td>NY</td></tr>
<tr><th><span class="am4shortcode">[am4user var=zip]</span></th><td>12334</td></tr>
<tr><th><span class="am4shortcode">[am4user var=country]</span></th><td>US</td></tr>
<tr><th><span class="am4shortcode">[am4user var=phone]</span></th><td>123-123-1234</td></tr>
</table>



