<?php _e("Block within [am4guest] tags will be displayed only for guest users(user's who is not logged in)", 'am4-plugin');?><br/>
<?php _e('If you specify also notactive attribute, text will be displayed for users who is logged in but is not active in aMember.', 'am4-plugin');?><br/>
<b><?php _e('Usage Example', 'am4-plugin');?></b><br/>
<b>[am4guest]</b><?php _e('Welcome guest user! Please login here:', 'am4-plugin');?> <b>[am4info var=loginurl]</b> <b>[/am4guest]</b><br/><br/>