<table class="form-table">
    <?php foreach($options as $name=>$value) : ?>
        <tr class="option-head">
            <th><label><?php echo $name;?>&nbsp;<a href="#"><?php _e('edit', 'am4-plugin');?></a></label></th>
        </tr>
        <tr class="option-body" style='display: none;'>
            <td><textarea class ="option-body-text" rows="20" cols="100" name='options[<?php echo $name;?>]'><?php echo $value;?></textarea></td>
        </tr>
    <?php endforeach; ?>
</table>
<br/>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('.option-head').click(function (){
            jQuery('.option-body').hide(200);
            jQuery(this).next('.option-body').show(200);
        });
        jQuery('.option-body-text').tabby();
    });
</script>
